# Generated by Django 5.1.4 on 2024-12-14 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_question_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='answeroption',
            name='question',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='course_cour_categor_ce9f5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='course_cour_teacher_dc98d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='course_cour_level_9054a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='courselanguages',
            name='course_cour_languag_4acb5c_idx',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Начальный', 'начальный'), ('Средний', 'средний'), ('Продвинутый', 'продвинутый')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_level',
            field=models.CharField(choices=[('Beginner', 'beginner'), ('Intermediate', 'intermediate'), ('Advanced', 'advanced')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='social_links',
            field=models.URLField(blank=True, verbose_name='Ссылки на соцсети'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.question'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_options',
            field=models.ManyToManyField(to='course.answer'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='favoritelesson',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.favorite'),
        ),
        migrations.AddField(
            model_name='favoritelesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
        migrations.DeleteModel(
            name='AnswerOption',
        ),
    ]
