# Generated by Django 5.1.4 on 2024-12-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_answer_favorite_favoritelesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favoritelesson',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='favoritelesson',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_options',
            field=models.ManyToManyField(to='course.useranswer'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='FavoriteLesson',
        ),
    ]
